# Generated by Django 4.2.6 on 2023-10-30 19:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('support_groups', '0002_remove_supportgroups_moderator'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserSupportGroup',
            new_name='Membership',
        ),
    ]
