# Generated by Django 4.2.6 on 2023-10-23 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0003_appuser_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='likes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='mood',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
