# Generated by Django 4.2.6 on 2023-10-30 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0004_appuser_likes_appuser_mood'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='last_login_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='login_streak',
            field=models.IntegerField(default=0),
        ),
    ]
